### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by yogiyio** [Hackeinstein/smtp-to-sms#7]
I keep receiving this error message

STARTING MAILER CHANNEL 0
STARTING MAILER CHANNEL 1
STARTING MAILER CHANNEL 2

Exception in thread Thread-1 (run_send):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1073, in _bootstrap_inner
Exception in thread Thread-2 (run_send):
Traceback (most recent call last):
    self.run()
DONE....  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1073, in _bootstrap_inner
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1010, in run
    self.run()
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1010, in run
  File "C:\Users\Owner\Downloads\smtp-to-sms-main\smtp-to-sms-main\1.0.0\main.py", line 174, in run_send
    self._target(*self._args, **self._kwargs)
    print(send_message(smtp=smtp, _from=_from, to=lead, subject=subject, content=randomize(content,start,stop)),reply_to)
  File "C:\Users\Owner\Downloads\smtp-to-sms-main\smtp-to-sms-main\1.0.0\main.py", line 174, in run_send
                                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    print(send_message(smtp=smtp, _from=_from, to=lead, subject=subject, content=randomize(content,start,stop)),reply_to)
  File "C:\Users\Owner\Downloads\smtp-to-sms-main\smtp-to-sms-main\1.0.0\main.py", line 71, in randomize
                                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    text = text.replace("[amount]",str(random_amount(start,end)))
  File "C:\Users\Owner\Downloads\smtp-to-sms-main\smtp-to-sms-main\1.0.0\main.py", line 71, in randomize
                                       ^^^^^^^^^^^^^^^^^^^^^^^^
    text = text.replace("[amount]",str(random_amount(start,end)))
  File "C:\Users\Owner\Downloads\smtp-to-sms-main\smtp-to-sms-main\1.0.0\main.py", line 47, in random_amount
                                       ^^^^^^^^^^^^^^^^^^^^^^^^
    return random.randint(start,end)
  File "C:\Users\Owner\Downloads\smtp-to-sms-main\smtp-to-sms-main\1.0.0\main.py", line 47, in random_amount
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\random.py", line 336, in randint
    return random.randint(start,end)
    return self.randrange(a, b+1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\random.py", line 336, in randint
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\random.py", line 301, in randrange
    return self.randrange(a, b+1)
    istart = _index(start)
           ^^^^^^^^^^^^^^^^^^^^^^
             ^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\random.py", line 301, in randrange
TypeError: 'float' object cannot be interpreted as an integer
    istart = _index(start)
             ^^^^^^^^^^^^^
TypeError: 'float' object cannot be interpreted as an integer

Can you point me to what I am doing wrong

**Comment by Hackeinstein** [comment]
Possibly your not filling some things right that’s why the modules have
having issues with the type of input you set in

**Comment by yogiyio** [comment]
![help](https://github.com/Hackeinstein/smtp-to-sms/assets/173191314/b8f79d10-0cae-4614-aea6-c7a12cd1eba7)
this is a picture of what I input if it helps

**Comment by Hackeinstein** [comment]
You possibly didn’t load multiple smtp

**Comment by Hackeinstein** [comment]
And if you fill it with rubbish it’ll crash so idk what you’re on

**Comment by yogiyio** [comment]
i did load multiple smtp, and tried to switch up the inputs still same error, If you can help me fix this I will send you some monero, this is for a big project of mine
